### PR TITLE
feature: vectorise escape helper function

### PR DESCRIPTION
**Pull request by DyfanJones**
This method vectorises current `escape` implementation.

Addresses speed issue from ticket: https://github.com/paws-r/paws/issues/400

### CODE REVIEW

**Comment by DyfanJones** [comment]
Double checking vectorised escape function works the same as existing for each mode.

``` r
# Escape characters given a pattern
paws_url_encode = function(string, pattern){
  vapply(string, function(string){
    x <- strsplit(string, "")[[1L]]
    z <- grep(pattern, x)
    if (length(z)) {
      y <- vapply(x[z], function(x) {
        paste0("%", toupper(as.character(charToRaw(x))),collapse = "")
      }, "")
      x[z] <- y
    }
    paste(x, collapse = "")
  }, character(1), USE.NAMES = FALSE)
}

# Escape strings so they can be safely included in a URL.
escape <- function(string, mode){
  base_url_encode = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789._~-"
  if (mode == "encodeHost" || mode == "encodeZone") {
    ignore_pattern = "][!$&'()*+,;=:<>\""
    pattern = paste0(ignore_pattern, base_url_encode)
    return(
      paws_url_encode(
        string, paste0("[^", pattern, "]")
      ))
  }
  
  ignore_pattern = "$&+,/;:=?@"
  pattern = paste0(ignore_pattern, base_url_encode)
  
  if (mode == "encodePath") {
    rm_pattern = "[?]"
    pattern = gsub(rm_pattern, "", pattern)
    return(paws_url_encode(string, paste0("[^", pattern, "]")))
  }
  if (mode == "encodePathSegment") {
    rm_pattern = "[/;,?]"
    pattern = gsub(rm_pattern, "", pattern)
    return(paws_url_encode(string, paste0("[^", pattern, "]")))
  }
  if (mode == "encodeQueryComponent") {
    return(paws_url_encode(gsub(" ", "+", string), paste0("[^", base_url_encode, "]")))
  }
  if (mode == "encodeFragment") {
    return(paws_url_encode(string, paste0("[^", pattern, "]")))
  }
  return(utils::URLencode(string, reserved = TRUE))
}

escape_mode = c("encodeHost", "encodeZone","encodePath", "encodePathSegment", "encodeQueryComponent", "encodeFragment")
string <- "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-._~`!@#$%^&*()=+[{]}\\|;:'\",<>/?"
setNames(
  lapply(escape_mode, function(mode){
    list(
      "new_method" = escape(string,mode),
      "old_method" = paws.common:::escape(string,mode)
    )
  }),
  escape_mode
)
#> $encodeHost
#> $encodeHost$new_method
#> [1] "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-._~%60!%40%23$%25%5E&*()=+[%7B]%7D%5C%7C;:'\",<>%2F%3F"
#> 
#> $encodeHost$old_method
#> [1] "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-._~%60!%40%23$%25%5E&*()=+[%7B]%7D%5C%7C;:'\",<>%2F%3F"
#> 
#> 
#> $encodeZone
#> $encodeZone$new_method
#> [1] "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-._~%60!%40%23$%25%5E&*()=+[%7B]%7D%5C%7C;:'\",<>%2F%3F"
#> 
#> $encodeZone$old_method
#> [1] "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-._~%60!%40%23$%25%5E&*()=+[%7B]%7D%5C%7C;:'\",<>%2F%3F"
#> 
#> 
#> $encodePath
#> $encodePath$new_method
#> [1] "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-._~%60%21@%23$%25%5E&%2A%28%29=+%5B%7B%5D%7D%5C%7C;:%27%22,%3C%3E/%3F"
#> 
#> $encodePath$old_method
#> [1] "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-._~%60%21@%23$%25%5E&%2A%28%29=+%5B%7B%5D%7D%5C%7C;:%27%22,%3C%3E/%3F"
#> 
#> 
#> $encodePathSegment
#> $encodePathSegment$new_method
#> [1] "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-._~%60%21@%23$%25%5E&%2A%28%29=+%5B%7B%5D%7D%5C%7C%3B:%27%22%2C%3C%3E%2F%3F"
#> 
#> $encodePathSegment$old_method
#> [1] "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-._~%60%21@%23$%25%5E&%2A%28%29=+%5B%7B%5D%7D%5C%7C%3B:%27%22%2C%3C%3E%2F%3F"
#> 
#> 
#> $encodeQueryComponent
#> $encodeQueryComponent$new_method
#> [1] "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-._~%60%21%40%23%24%25%5E%26%2A%28%29%3D%2B%5B%7B%5D%7D%5C%7C%3B%3A%27%22%2C%3C%3E%2F%3F"
#> 
#> $encodeQueryComponent$old_method
#> [1] "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-._~%60%21%40%23%24%25%5E%26%2A%28%29%3D%2B%5B%7B%5D%7D%5C%7C%3B%3A%27%22%2C%3C%3E%2F%3F"
#> 
#> 
#> $encodeFragment
#> $encodeFragment$new_method
#> [1] "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-._~%60%21@%23$%25%5E&%2A%28%29=+%5B%7B%5D%7D%5C%7C;:%27%22,%3C%3E/?"
#> 
#> $encodeFragment$old_method
#> [1] "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-._~%60%21@%23$%25%5E&%2A%28%29=+%5B%7B%5D%7D%5C%7C;:%27%22,%3C%3E/?"
```

<sup>Created on 2022-06-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by DyfanJones** [comment]
@adambanker @davidkretch When you have some free time do you mind reviewing this PR.

Many thanks in advanced :)

**Comment by davidkretch** [comment]
This is really great. I think my comments are really just about making some names a little clearer.

So sorry for the delay :-(

**Comment by DyfanJones** [comment]
@davidkretch I have updated some of the names, and added some comments to help explain what each section is doing :)

**Comment by davidkretch** [comment]
Thanks, the added comments are good, but I think some of of the line level issues are still outstanding. I think in particular url.R line 88 (`return(paste(lapply(sort(names(param_filter)), ...` and 141-147 (with variables x, y, and z) are maintainability issues.

**Comment by DyfanJones** [comment]
I have been thinking about this even more and I think we can squeeze even more performance out of it.

``` r
# Escape strings so they can be safely included in a URL.
escape_v2 <- function(string, mode){
  base_url_encode = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789._~-"
  if (mode == "encodeHost" || mode == "encodeZone") {
    ignore_pattern = "][!$&'()*+,;=:<>\""
    pattern = paste0(ignore_pattern, base_url_encode)
    return(
      paws_url_encode_v2(
        string, paste0("[^", pattern, "]")
      ))
  }
  
  ignore_pattern = "$&+,/;:=?@"
  pattern = paste0(ignore_pattern, base_url_encode)
  
  if (mode == "encodePath") {
    rm_pattern = "[?]"
    pattern = gsub(rm_pattern, "", pattern)
    return(paws_url_encode_v2(string, paste0("[^", pattern, "]")))
  }
  if (mode == "encodePathSegment") {
    rm_pattern = "[/;,?]"
    pattern = gsub(rm_pattern, "", pattern)
    return(paws_url_encode_v2(string, paste0("[^", pattern, "]")))
  }
  if (mode == "encodeQueryComponent") {
    return(paws_url_encode_v2(gsub(" ", "+", string), paste0("[^", base_url_encode, "]")))
  }
  if (mode == "encodeFragment") {
    return(paws_url_encode_v2(string, paste0("[^", pattern, "]")))
  }
  return(utils::URLencode(string, reserved = TRUE))
}

paws_url_encode_v2 <- function(string, pattern){
  vapply(string, function(string){
    # split string out into individual characters
    chars <- strsplit(string, "")[[1L]]
    # find characters that match pattern
    found <- grep(pattern, chars)
    if (length(found)) {
      # encode found characters only
      chars[found] <- toupper(paste0("%", charToRaw(string)[found]))
    }
    # rebuild string with encoded characters
    paste(chars, collapse = "")
  }, character(1), USE.NAMES = FALSE)
}

escape_mode = c("encodeHost", "encodeZone","encodePath", "encodePathSegment", "encodeQueryComponent", "encodeFragment")
string <- "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-._~`!@#$%^&*()=+[{]}\\|;:'\",<>/?"
large_string <- paste(rep(string, 1000), collapse = "")

bm <- bench::mark(
  # method developed above
  vapply_chartoraw = lapply(escape_mode, function(mode) paws.common:::escape(large_string, mode)),
  filter_raw = lapply(escape_mode, function(mode) escape_v2(large_string, mode)),
  iterations = 500
)
#> Warning: Some expressions had a GC in every iteration; so filtering is disabled.

bm |> ggplot2::autoplot()
#> Loading required namespace: tidyr
```



<sup>Created on 2022-07-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

This new method runs faster due to `charToRaw` only being called once. We then can filter the raw object when encoding. This results in a vapply being removed (plus I think it makes the code look a little neater). I believe we have managed to get a performance improvement from 100.2 seconds (original escape code) to 0.1 second (PR escape code).

**Comment by DyfanJones** [comment]
Just for completeness here is some performance enhancements for the url decoding side of things. 

```r
paws_url_encoder <- function(string, pattern){
  vapply(string, function(string){
    # split string out into individual characters
    chars <- strsplit(string, "")[[1L]]
    # find characters that match pattern
    found <- grep(pattern, chars)
    if (length(found)) {
      # encode found characters only
      chars[found] <- paste0("%", charToRaw(string)[found])
    }
    # rebuild string with encoded characters
    paste(chars, collapse = "")
  }, character(1), USE.NAMES = FALSE)
}

paws_url_decoder = function(url) {
  # split string into separate characters
  chars = strsplit(url, "")[[1]]
  
  # locate % position
  found = grep("%", chars, fixed = TRUE)
  
  if (length(found)) {
    start = found + 1
    end = found + 2
    
    # get raw vector of encoded parts (character form)
    # for example: "%20" -> "20"
    encoded = vapply(seq_along(start), function(i) {
        paste0(chars[start[i]:end[i]], collapse = "")
      }, FUN.VALUE = character(1)
    )
    # remove encoded parts from chars
    rm = c(start, end)
    
    # update character % position
    found = grep("%", chars[-rm], fixed = TRUE)
    
    # convert split url to raw
    char_raw = charToRaw(paste(chars[-rm], collapse=""))
    
    # replace character % with decoded parts
    char_raw[found] <- as.raw(as.hexmode(encoded))
    
    return(rawToChar(char_raw))
  }
  return(url)
}

string <- "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-._~`!@#$%^&*()=+[{]}\\|;:'\",<>/? "
pattern <- "[^ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789._~-]"

url = paste(sample(strsplit(string, "")[[1]], 1e6, replace = T), collapse = "")
url_encode = paws_url_encoder(url, pattern)

> system.time({out = paws_url_decoder(url_encode)})
# user  system elapsed 
# 0.658   0.015   0.672 

> system.time({out2 = URLdecode(url_encode)})
# user  system elapsed 
# 494.960  29.872 524.682 

url == out
# TRUE

url == out2
# TRUE
```

I will add some unit tests for the decoder.

**Comment by DyfanJones** [comment]
@davidkretch let me know what you think about the changes. I think we are a good place with the new performance enhancements. Let me know if you can see any outstanding issues 😄

**Comment by davidkretch** [comment]
Looks good. Very nice perf improvement!

**Pull request merged**
