### PR TITLE
Move common functions to package paws.common

### PR DESCRIPTION
**Pull request by davidkretch**
* Move common functions out of codegen and each generated package into R package `paws.common`.

### CODE REVIEW

**Comment by adambanker** [comment]
@davidkretch, can you explain why the generated packages still copy a lot of the code? For instance, if I run, `make install-paws.ec2` the result still has handlers like handler_restjson.R in it.

**Comment by davidkretch** [comment]
make.paws isn’t updated. Its tests will fail until paws.common is in master. Otherwise it will try to fetch paws.common and fail.

**Comment by adambanker** [comment]
So are the generated packages not using paws.common then?

**Comment by davidkretch** [comment]
Right, they won’t use them until make.paws is also updated.

**Pull request merged**
