### PR TITLE
Check the container role for credentials before the instance role

### PR DESCRIPTION
**Pull request by adambanker**
It checks if the associated job role has credentials before checking the instance role. This pull request addresses #226. I tested it by running a batch job with the cran version of paws, as well as with my branch and it only worked on my branch as expected. I also tested out my branch on an ec2 instance with a proper role.

One issue is that running paws on an ec2 instance with a role takes longer because it needs to wait for the job role check to time out first. Let me know if you have any ideas for how to improve this.

### CODE REVIEW

**Comment by ryanb8** [comment]
To avoid the timeout issue, can we avoid making the request to the credentials_uri if the environment variable is empty? I believe R defaults to `''` if the environment variable is not present.

**Comment by adambanker** [comment]
@ryanb8, great call with checking the environment variable! That worked

**Comment by adambanker** [comment]
@davidkretch I made the changes you requested

**Comment by davidkretch** [comment]
I was wrong about how much code they shared, but this works for me and I think this is the right approach.

**Pull request merged**
