### PR TITLE
Initial implementation of standard retry

### PR DESCRIPTION
**Pull request by DyfanJones**
This PR implements standard retry (https://github.com/boto/boto3/blob/0b82bf9843ad6d350b48442c47f4a484a886ee3f/docs/source/guide/retries.rst#standard-retry-mode).

Address Ticket: https://github.com/paws-r/paws/issues/520

### CODE REVIEW

**Comment by DyfanJones** [comment]
@davidkretch @adambanker Am I going crazy but it looks like this implements the standard retries logic: https://github.com/boto/boto3/blob/0b82bf9843ad6d350b48442c47f4a484a886ee3f/docs/source/guide/retries.rst#standard-retry-mode

**Comment by wlandau** [comment]
Thanks for working on this!

How do I configure `max_retries` for S3? Are there other retry-related settings? 

I ran my tests in `targets`, and I notice some new errors, one of which happens when I try to delete a bucket.

```r
random_bucket_name <- function() {
  paste0(
    "targets-test-bucket-",
    substr(
      digest::digest(tempfile(), algo = "sha256"),
      start = 0,
      stop = 43
    )
  )
}

aws_s3_delete_bucket <- function(bucket, client = paws.storage::s3()) {
  region <- client$get_bucket_location(Bucket = bucket)
  old <- Sys.getenv("AWS_REGION")
  on.exit(Sys.setenv(AWS_REGION = old))
  Sys.setenv(AWS_REGION = region)
  out <- client$list_object_versions(Bucket = bucket)
  for (x in out$Versions) {
    args <- list(
      Bucket = bucket,
      Key = x$Key
    )
    has_version_id <- !identical(x$VersionId, "null") &&
      !identical(x$VersionId, character(0))
    if (has_version_id) {
      args$VersionId <- x$VersionId
    }
    do.call(client$delete_object, args)
  }
  client$delete_bucket(Bucket = bucket)
}

bucket <- random_bucket_name()
paws.storage::s3()$create_bucket(Bucket = bucket)

aws_s3_delete_bucket(bucket)
#> Error: SignatureDoesNotMatch (HTTP 403). The request signature we calculated does not match the signature you provided. Check your key and signing method.

traceback()
#> 8: stop(error)
#> 7: handler$fn(request)
#> 6: run(request, retry)
#> 5: retry(request)
#> 4: send_request(request)
#> 3: (function (Bucket, Key, MFA = NULL, VersionId = NULL, RequestPayer = NULL, 
#>        BypassGovernanceRetention = NULL, ExpectedBucketOwner = NULL) 
#>    {
#>        op <- new_operation(name = "DeleteObject", http_method = "DELETE", 
#>            http_path = "/{Bucket}/{Key+}", paginator = list())
#>        input <- .s3$delete_object_input(Bucket = Bucket, Key = Key, 
#>            MFA = MFA, VersionId = VersionId, RequestPayer = RequestPayer, 
#>            BypassGovernanceRetention = BypassGovernanceRetention, 
#>            ExpectedBucketOwner = ExpectedBucketOwner)
#>        output <- .s3$delete_object_output()
#>        config <- get_config()
#>        svc <- .s3$service(config)
#>        request <- new_request(svc, op, input, output)
#>        response <- send_request(request)
#>        return(response)
#>    })(Bucket = "targets-test-bucket-31d505c5eea61275e72b1a7db3463315c802bdba014", 
#>        Key = list(), VersionId = list())
#> 2: do.call(client$delete_object, args) at helper-aws.R#37
#> 1: aws_s3_delete_bucket(bucket)#> 
```

**Comment by DyfanJones** [comment]
Hmm that is a pain that must of slipped in from the PR https://github.com/paws-r/paws/pull/621. When I identify the issue I will update the units tests to ensure it doesn't happen again 😄

**Comment by wlandau** [comment]
Thanks! Happy to test again when you are ready.

`targets` has a `max_tries` setting for this, and it currently does its own retry algorithm. I can switch `max_tries` to delegate to `paws.common` when the time comes. What kind of argument or setting would I use? Something like `paws.storage::s3(config = list(tries = 5))`?

**Comment by DyfanJones** [comment]
Ah sorry I didn't say how to change the max retries.

```r
# paws v-0.3.0
library(paws)
library(paws.common)

client <- s3(config(max_retries = 5))

# or 
client <- s3(config = list(max_retries = 5))


# paws v-0.4.0+
library(paws)

client <- s3(config(max_retries = 5))

# or 
client <- s3(config = list(max_retries = 5))
```

By default it will set the max retries to 3 to match boto3 documentation: https://github.com/boto/boto3/blob/0b82bf9843ad6d350b48442c47f4a484a886ee3f/docs/source/guide/retries.rst#standard-retry-mode


I believe the bug is coming some where in the s3 unmarshal functions when it decodes the xml. I haven't pin point it just yet, hopefully it is a simple fix 😄

**Comment by DyfanJones** [comment]
Ah I have found the issue. Well it isn't an issue more of an "hmmm what approach should paws take on this".

Previously paws would return and empty list for xml list objects even if it had nested content. 

# paws.common 0.5.8
``` r
bucket <- "empty-bucket"
client <- paws.storage::s3()
out <- client$list_object_versions(Bucket = bucket)
out$Versions
#> list()
```

<sup>Created on 2023-08-29 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

The latest version of paws.common will build the default values for all list, map, structures. 

# paws.common 0.5.9
``` r
bucket <- "empty-bucket"
client <- paws.storage::s3()
out <- client$list_object_versions(Bucket = bucket)
out$Versions
#> [[1]]
#> [[1]]$ETag
#> list()
#> 
#> [[1]]$ChecksumAlgorithm
#> [[1]]$ChecksumAlgorithm[[1]]
#> list()
#> 
#> 
#> [[1]]$Size
#> numeric(0)
#> 
#> [[1]]$StorageClass
#> list()
#> 
#> [[1]]$Key
#> list()
#> 
#> [[1]]$VersionId
#> list()
#> 
#> [[1]]$IsLatest
#> logical(0)
#> 
#> [[1]]$LastModified
#> POSIXct of length 0
#> 
#> [[1]]$Owner
#> [[1]]$Owner[[1]]
#> [[1]]$Owner[[1]]$DisplayName
#> list()
#> 
#> [[1]]$Owner[[1]]$ID
#> list()
```

<sup>Created on 2023-08-29 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

So technically paws.common 0.5.9 is returning a more accurate default view: https://www.paws-r-sdk.com/docs/s3_list_object_versions/#value

So for your example @wlandau, paws is putting empty Key and VersionId in the `do.call(client$delete_object, args)` which will cause an error (not a great error though).

We can a couple of options:

1. Simplify paws.common 0.5.9 default output to replication 0.5.8
2. Take boto3 approach and don't have any default output
3. Embrase paws.common 0.5.9 enriched output.

**Comment by DyfanJones** [comment]
My gut feeling is to simplify paws.common 0.5.9 defaults to match 0.5.8. @wlandau, @davidkretch, @adambanker do you have an opinion on this :)

**Comment by wlandau** [comment]
If I understand correctly, that is the more back-compatible approach and will help me avoid refactoring 'targets'. So unless I am missing something, I like it.

**Comment by DyfanJones** [comment]
@wlandau yes that is correct. I will have to look how easy it is to implement :)

**Comment by DyfanJones** [comment]
Next steps if `targets` unit tests work ok :)

- Update paginate unit tests:
    - remove retry logic (deprecated in favour of general retry logic)
- Add unit tests for new retry logic
- Add unit test for xml_parse for nested structures/list etc... when parent needs to be flattened (issue identified)

**Comment by wlandau** [comment]
Thanks for working on this, @DyfanJones. Almost all of the unit tests in `targets` are passing now, only multipart uploads are struggling. On my end, the example at https://github.com/paws-r/paws/blob/main/examples/s3_multipart_upload.R errors out with:

```r
Error : C stack usage  7954104 is too close to the limit

> traceback()
3: readBin(con, what = "raw", n = file.size(tmp))
2: .s3$upload_part_input(Body = Body, Bucket = Bucket, ContentLength = ContentLength, 
       ContentMD5 = ContentMD5, ChecksumAlgorithm = ChecksumAlgorithm, 
       ChecksumCRC32 = ChecksumCRC32, ChecksumCRC32C = ChecksumCRC32C, 
       ChecksumSHA1 = ChecksumSHA1, ChecksumSHA256 = ChecksumSHA256, 
       Key = Key, PartNumber = PartNumber, UploadId = UploadId, 
       SSECustomerAlgorithm = SSECustomerAlgorithm, SSECustomerKey = SSECustomerKey, 
       SSECustomerKeyMD5 = SSECustomerKeyMD5, RequestPayer = RequestPayer, 
       ExpectedBucketOwner = ExpectedBucketOwner)
1: client$upload_part(Body = readBin(con, what = "raw", n = file.size(tmp)), 
       Bucket = bucket, Key = "x", PartNumber = 1, UploadId = upload$UploadId)
```

**Comment by DyfanJones** [comment]
ah so close 😆 @wlandau  Thanks for the testing. I will need to enrich the unit tests to catch these edge cases as well :)

**Comment by wlandau** [comment]
Thanks for the updates. All my tests pass now.

**Comment by DyfanJones** [comment]
I believe I have got a working solution for native retries.

Here is an example where I throttle AWS and it successfully retries.

``` r
remotes::install_github("DyfanJones/paws/paws.common", ref = "native_retry")
install.packages('paws', repos = c(pawsr = 'https://paws-r.r-universe.dev', CRAN = 'https://cloud.r-project.org'))

library(paws)

client <- sagemaker()
resp <- client$list_processing_jobs() |> paginate()

#> ERROR [2023-08-31 15:44:41.206]: Request failed. Retrying in 0.016 seconds...
#> ERROR [2023-08-31 15:44:41.229]: Request failed. Retrying in 3.026 seconds...
#> ERROR [2023-08-31 15:44:44.289]: Request failed. Retrying in 2.505 seconds...
#> Error: ThrottlingException (HTTP 400). Rate exceeded
```

<sup>Created on 2023-08-31 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by DyfanJones** [comment]
After looking at botocore's standard retrier (https://github.com/boto/botocore/blob/71a80e4dd9428351bbdcd0c1a06fbcc70bb091b4/botocore/retries/standard.py) I believe I am not a million miles away with this implementation. I will add some unit tests and I think we will have an initial native retrier :)

**Comment by wlandau** [comment]
Thank you so much, @DyfanJones! I will begin migrating `targets` to use native retries in `paws`.

**Comment by DyfanJones** [comment]
Thanks for all the testing you did @wlandau. I am currently in the process in checking if the latest changes breaks any dependent packages. I have marked `targets` as working correctly https://github.com/paws-r/paws/issues/657 however if this isn't true please let me know.

**Comment by wlandau** [comment]
Absolutely! Coincidentally, this a convenient time for me to do testing because of https://github.com/ropensci/targets/pull/1130 (c.f. https://books.ropensci.org/targets/cloud-storage.html).

I just migrated `targets` to use `s3(config = list(max_retries = ...))`, and although I am not sure how to test the actual retrying mechanism using only S3, my test suite works with both CRAN `paws.common` and with `remotes::install_github("dyfanjones/paws/paws.common")` (https://github.com/paws-r/paws/commit/6c28ed42709993b8696116dbb6f7ce9e805f0686).

**Pull request merged**
