### PR TITLE
ON HOLD: Clean output objects

### PR DESCRIPTION
**Pull request by davidkretch**
* Remove all tag metadata from AWS response objects given to the user. Add `get_request_output()` to get the output from the request object and remove tags. (#35)
* Improve the tag metadata functions and collect them in `tags.R`.
* Fix two REST XML tests which did not use the shape builder functions (`Structure()` etc.) and broke when the tag implementation changed.
* Delete the underscore element and code that assumed one existed. (#41)

### CODE REVIEW

**Comment by adambanker** [comment]
I tried running the s3 operation put_bucket_tagging with these changes, and it populated the inputs in the wrong places.

My example:
```
(a <- put_bucket_tagging(
  Bucket = "Name-of-My-Bucket",
  Tagging = list(
    TagSet = list(
      list(
        Key = "Dog",
        Value = "Westie"
      ),
      list(
        Key = "Dog2",
        Value = "Beagle"
      )
    )
  )
))
```
The params looked like:
```
$Bucket
[1] "Name-of-My-Bucket"

$ContentMD5
$ContentMD5$TagSet
$ContentMD5$TagSet[[1]]
$ContentMD5$TagSet[[1]]$Key
[1] "Dog"

$ContentMD5$TagSet[[1]]$Value
[1] "Westie"


$ContentMD5$TagSet[[2]]
$ContentMD5$TagSet[[2]]$Key
[1] "Dog2"

$ContentMD5$TagSet[[2]]$Value
[1] "Beagle"




$Tagging
NULL

attr(,"tags")
attr(,"tags")$shape
[1] "PutBucketTaggingRequest"

attr(,"tags")$type
[1] "structure"

attr(,"tags")$required
attr(,"tags")$required[[1]]
[1] "Bucket"

attr(,"tags")$required[[2]]
[1] "Tagging"


attr(,"tags")$members
attr(,"tags")$members$Bucket
attr(,"tags")$members$Bucket$shape
[1] "BucketName"

attr(,"tags")$members$Bucket$location
[1] "uri"

attr(,"tags")$members$Bucket$locationName
[1] "Bucket"


attr(,"tags")$members$ContentMD5
attr(,"tags")$members$ContentMD5$shape
[1] "ContentMD5"

attr(,"tags")$members$ContentMD5$location
[1] "header"

attr(,"tags")$members$ContentMD5$locationName
[1] "Content-MD5"


attr(,"tags")$members$Tagging
attr(,"tags")$members$Tagging$shape
[1] "Tagging"

attr(,"tags")$members$Tagging$locationName
[1] "Tagging"

attr(,"tags")$members$Tagging$xmlNamespace
attr(,"tags")$members$Tagging$xmlNamespace$uri
[1] "http://s3.amazonaws.com/doc/2006-03-01/"




attr(,"tags")$payload
[1] "Tagging"
```

**Comment by davidkretch** [comment]
The first time I ran the example I saw the same thing, but it looked like it was using old code. It worked when I re-ran `make codegen` and `make install-paws-s3`. Can you see if that works for you.

I also fixed what I think is a separate issue in that it was keeping unnecessarily large amount in the tags, including a second copy of the list of parameters.

**Comment by davidkretch** [comment]
This can wait until REST XML is done and merged.

**Comment by adambanker** [comment]
I am still getting the same issue, but with less tags now

**Pull request closed without merging**
