### PR TITLE
Undo sub categories

### PR DESCRIPTION
**Pull request by davidkretch**
* Update packages.yml to remove the sub-category packages.
* Shorten RD names and add aliases, to avoid CRAN check warnings about invalid overly-long file names.
* Regenerate Paws without sub-categories.

### CODE REVIEW

**Comment by davidkretch** [comment]
cc @DyfanJones

**Comment by DyfanJones** [comment]
did you apply the shortened r documentation name (hard to tell :P)

**Comment by davidkretch** [comment]
I still have to do that. Will get to it later today.

**Comment by DyfanJones** [comment]
Sorry for my naive question, @davidkretch is the shortened r documentation going to be apart of this PR or the next?

**Comment by davidkretch** [comment]
Sorry it’s going to be in this one. I haven’t pushed it to GitHub yet.

**Comment by davidkretch** [comment]
@DyfanJones this should be ready to go.

**Pull request merged**
