### PR TITLE
Support custom configuration per service

### PR DESCRIPTION
**Pull request by adambanker**

### CODE REVIEW

**Comment by adambanker** [comment]
@davidkretch I got it to create custom services so it does not just overwrite the service in the package name space.

Accordingly
```
ec2east <- paws::ec2(config = list(region = "us-east-1"))
ec2west <- paws::ec2(config = list(region = "us-west-1"))

ec2east$describe_instances()
ec2west$describe_instances()
```
produce different results.

Let me know if you want to scale back the scope of this commit. Thanks

**Comment by adambanker** [comment]
@davidkretch I have addressed your issues

**Comment by davidkretch** [comment]
Unfortunately tooltips no longer appear in RStudio.  Tooltips also don't appear in the previous version (with the `.svc` parameter) and don't appear in a version using R6 classes.

**Comment by adambanker** [comment]
@davidkretch can you give an example?

**Comment by davidkretch** [comment]
If you run the following and hit tab, no tooltips will appear for the operations.

```
acm <- paws::acm()
acm$
```

If you run the following and hit tab, no tooltips will appear for the parameters.

```
acm$add_tags_to_certificate(
```

**Comment by adambanker** [comment]
Are you sure it isn't an issue with something else?
paws_tooltip

**Comment by davidkretch** [comment]
The tooltips taken from the documentation is what is missing.  This is what it should look like:
image

**Pull request closed without merging**
