### PR TITLE
Manually fix disallowed characters

### PR DESCRIPTION
**Pull request by davidkretch**
## This PR

Manually remove characters that are causing notes and warnings in CRAN check, namely:
* `\#` -- replace with `#`
* `\u2028` Unicode line separator -- remove entirely

e.g. https://www.r-project.org/nosvn/R.check/r-devel-windows-x86_64/paws.compute-00check.html
```
checking Rd files ... [65s] NOTE
checkRd: (-1) ec2_create_key_pair.Rd:39: Escaped LaTeX specials: \#
checkRd: (-1) ec2_create_security_group.Rd:18: Escaped LaTeX specials: \#
checkRd: (-1) ec2_create_security_group.Rd:27: Escaped LaTeX specials: \#
```

```
checking PDF version of manual ... [90s] WARNING
LaTeX errors when creating PDF version.
This typically indicates Rd problems.
LaTeX errors found:
! Package inputenc Error: Unicode character   (U+2028)
(inputenc) not set up for use with LaTeX.
```

## Test plan
Run CRAN check on all packages:
```r
checks <- list()
sink(tempfile())
for (package in list.dirs("../cran", recursive = FALSE)) {
  checks[[package]] <- devtools::check(package, cran = TRUE)
}
sink()

for (package in names(checks)) {
  cat(package)
  cat(": ")
  errors <- errors_warnings[[package]]$errors
  warnings <- errors_warnings[[package]]$warnings
  if (length(errors) == 0 && length(warnings) == 0) {
    cat("None")
  } else {
    cat("\n")
    cat(errors)
    cat("\n")
    cat(warnings)
  }
  cat("\n")
}
```

Output:
```
../cran/paws: 

checking dependencies in R code ... WARNING
Missing or unexported object: ‘paws.security.identity::sso’ checking Rd cross-references ... WARNING
Missing link or links in documentation object 'sso.Rd':
  ‘sso_get_role_credentials’ ‘sso_list_account_roles’
  ‘sso_list_accounts’ ‘sso_logout’

See section 'Cross-references' in the 'Writing R Extensions' manual.
../cran/paws.analytics: None
../cran/paws.application.integration: None
../cran/paws.business.applications: None
../cran/paws.compute: None
../cran/paws.cost.management: None
../cran/paws.customer.engagement: None
../cran/paws.database: None
../cran/paws.developer.tools: None
../cran/paws.end.user.computing: None
../cran/paws.game.development: None
../cran/paws.internet.of.things: None
../cran/paws.machine.learning: None
../cran/paws.management: None
../cran/paws.media.services: None
../cran/paws.migration: None
../cran/paws.mobile: None
../cran/paws.networking: None
../cran/paws.robotics: None
../cran/paws.security.identity: None
../cran/paws.storage: None
```

### CODE REVIEW

**Comment by davidkretch** [comment]
> Quick naive question, going forward would something as crude as `gsub("\#", "#", pattern)` need to be added to `make.paws`?

Good question -- it doesn't look like they're in the source documentation and make.paws isn't adding them now. So I suspect it was a Windows specific issue since I am no longer using Windows.

**Comment by davidkretch** [comment]
@DyfanJones I ran `devtools::check` on all the category packages and there are no errors or warnings so I think these are ok to submit to CRAN. There are some notes that I'll include in the CRAN comments. I'll update the version numbers and CRAN comments in a subsequent PR.

**Comment by DyfanJones** [comment]
> @DyfanJones I ran `devtools::check` on all the category packages and there are no errors or warnings so I think these are ok to submit to CRAN. Let me know if it is ok with you to merge.
> 
> There are some notes that I'll include in the CRAN comments. I'll update the version numbers and CRAN comments in a subsequent PR.

Should I push them to the cran so we get the maintainer update on the packages?

**Comment by davidkretch** [comment]
> > @DyfanJones I ran `devtools::check` on all the category packages and there are no errors or warnings so I think these are ok to submit to CRAN. Let me know if it is ok with you to merge.
> > There are some notes that I'll include in the CRAN comments. I'll update the version numbers and CRAN comments in a subsequent PR.
> 
> Should I push them to the cran so we get the maintainer update on the packages?

Yeah that works. I was just trying to save you a round of updates.

**Pull request merged**
